apiVersion: v1
kind: Service
metadata:
  name: anotherbrick-service
  labels:
    app: anotherbrick
spec:
  type:  NodePort
  ports: 
  - port: 80
    nodePort: 30006
    protocol: TCP
  selector:
    app: anotherbrick
